#Numpy

In [ ]:
#1. Creating a sparse Matrix
# Problem :
#Given data with very few nonzero values, you want to efficiently represent it.

import numpy as np
from scipy import sparse


#create a matrix
matrix = np.array([[0,0],
                  [0,1],
                  [3,0]])

#create compressed sparse matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [ ]:
# create large matrix
#csr = compressed sparse row
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

matrix_large_sparse = sparse.csr_matrix(matrix_large)

print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [ ]:
#2.You want to describe the shape, size and dimension of the Matrix
matrix = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

print("shape",matrix.shape)
print("size",matrix.size)
print("dimension",matrix.ndim)

shape (3, 4)
size 12
dimension 2


In [ ]:
#3. You want to apply some function to multiple elements in an array
# Use Numpy Vectorize

# Create matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

#Create function that adds 100 to something
add_100 = lambda i: i + 100

#create vectorized function
vectorized_add_100 = np.vectorize(add_100)

#apply function to all the elements in the matrix

vectorized_add_100(matrix)

"""NumPy’s vectorize class converts a function into a function that can apply to all elements
in an array or slice of an array. It’s worth noting that vectorize is essentially a
for loop over the elements and does not increase performance. Furthermore, NumPy
arrays allow us to perform operations between arrays even if their dimensions are not
the same (a process called broadcasting)."""

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [ ]:
#4. You want to calculate some descriptive statistics about an array

#mean,var,std
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("mean:",np.mean(matrix))
print("var",np.var(matrix))
print("std:",np.std(matrix))

# find the mean value in each column
print("Mean along column axis",np.mean(matrix,axis=0))

mean: 5.0
var 6.666666666666667
std: 2.581988897471611
Mean along column axis [4. 5. 6.]


In [ ]:
#5.You want to change the shape of the array(number of rows and columns) of an array
# without changing the element values

# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

print(matrix.reshape(2,6))

"""One useful argument in reshape is -1 which effectively means  "as many as needed",
so reshape(1,-1)  means one row and as many columns as needed"""

print(matrix.reshape(1,-1))

"""Finally, if we provide one interger, reshape  will return 1D array of 
that length"""

print(matrix.reshape(12))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#6. Flattening a Matrix
#You need to transform a matrix into a one-dimensional array.

matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

#flatten matrix
matrix.flatten()

"""Flatten is a simple  method to transform a matrix into a one-dimensional array. Alternatively, we can use 
reshape to create  a row vector """

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#7.Finding the rank of a matrix

#You need to know the rank of a matrix
# Create matrix
matrix = np.array([[1, 1, 1],
                  [1, 1, 10],
                  [1, 1, 15]])
np.linalg.matrix_rank(matrix)

"""The rank of a matrix is the dimensions of the vector space spanned by its columns or
rows. Finding the rank of a matrix is easy in NumPy thanks to matrix_rank"""


2

In [ ]:
#8. Calculating the determinant of the matrix

matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 8, 9]])

np.linalg.det(matrix)

0.0

In [ ]:
#9. Getting the diagonal of the matrix. 
# Create matrix
matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 8, 9]])

print(matrix.diagonal())

"""It is also possible to get a diagonal off from the main diagonal by using  the offset parameter"""

# return diagonal one above the main diagonal 
print(matrix.diagonal(offset=1))

# return diagonal one below the main diagonal 
print(matrix.diagonal(offset=-1))

[1 4 9]
[2 6]
[2 8]


In [ ]:
#10. Calculating the trace of the matrix
"""The trace of a matrix is the sum of the diagonal elements and is often used under the
hood in machine learning methods""" 
matrix = np.array([[1, 2, 3],
                  [2, 4, 6],
                  [3, 8, 9]])
print(matrix.trace())

print(sum(matrix.diagonal()))

14
14


In [ ]:
#11. Finding the eigen values and eigen vectors. 

# Create matrix
matrix = np.array([[1, -1, 3],
                  [1, 1, 6],
                  [3, 8, 9]])

# create eigenvalues and eigenvectors 

eigenvalues, eigenvectors =   np.linalg.eig(matrix)

#view Eigen values
print("eigenvalues","\n",eigenvalues)

#view eigen vectors
print("eigenvectors","\n",eigenvectors)

eigenvalues 
 [13.55075847  0.74003145 -3.29078992]
eigenvectors 
 [[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [ ]:
#12. You need to calculate the dot product of two vectors

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

print(np.dot(vector_a,vector_b))


vector_a @ vector_b

32


32

In [ ]:
#13. Subtracting matrix
# Create matrix
matrix_a = np.array([[1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
                    [1, 3, 1],
                    [1, 3, 8]])

np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [ ]:
#14. Multiple 2 matrices
# Create matrix
matrix_a = np.array([[1, 1],
                    [1, 2]])
# Create matrix
matrix_b = np.array([[1, 3],
                    [1, 2]])

print(np.dot(matrix_a,matrix_b))

#If we want to do element-wise multiplication, we can use the * operator:

print(matrix_a * matrix_b)

[[2 5]
 [3 7]]
[[1 3]
 [1 4]]


In [ ]:
#15. Inverting a matrix

matrix = np.array([[1, 4],
                  [2, 5]])

print(np.linalg.inv(matrix))

matrix @ np.linalg.inv(matrix)

[[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]


array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
#16.  You want to generate pseudorandom numbers 
"""Random processes with the same seed will
always produce the same output."""

np.random.seed(0)

print(np.random.random(3),"\n")

# Generate three random integers  between 1 and 10
print("Random Int","\n",np.random.randint(0,11,3),"\n")

#Alternately we can generate numbers by drawing them from a distribution

# Draw three numbers from a normal distribution with mean 0.0 and standard deviation 1.0
print("Normal Distribution","\n",np.random.normal(0.0,1.0,3),"\n")

#Draw three numbers from a logistic distribution with mean 0.0 and standard deviation 1.0 
print("Logistic Distribution","\n",np.random.logistic(0.0,1.0,3),"\n")

#Draw three numbers greater than 1.0 and less than 2.0
print("Uniform Distribution","\n",np.random.uniform(1.0,2.0,3))


[0.5488135  0.71518937 0.60276338] 

Random Int 
 [3 7 9] 

Normal Distribution 
 [-1.42232584  1.52006949 -0.29139398] 

Logistic Distribution 
 [-0.98118713 -0.08939902  1.46416405] 

Uniform Distribution 
 [1.47997717 1.3927848  1.83607876]
